app/ui/routes/__init__.py
from .auth import auth_blueprint
from .pages import pages_blueprint
from .services import services_blueprint

app/ui/routes/auth.py
from flask import Blueprint, request, flash, session, jsonify
from app.infra.actions import Login, Register
import uuid

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/login_service', methods=['POST'])
def login():
    username = request.form['username']
    password = request.form['password']

    LoginUser = Login(user=username, password=password)
    if LoginUser.login():
        session['loged_in'] = True
        session['uuid'] = LoginUser.get_uuid()
        
        return jsonify({'loged': True})
    
    flash('Não foi possiovel realizar o login')
    return jsonify({'loged': False})

@auth_blueprint.route('/register_service', methods=['POST'])
def register():
    username = request.form['username']
    password = request.form['password']

    RegisterUser = Register(userUuid=uuid.uuid4(), user=username, password=password)
    if RegisterUser.register():
        session['loged_in'] = True
        session['uuid'] = RegisterUser.get_uuid()

        return jsonify({'loged': True})
    
    flash('Não foi possiovel realizar o registro')
    return jsonify({'loged': False})

@auth_blueprint.route('/logout_service', methods=['POST'])
def logout():
    session.pop('loged_in', None)
    session.pop('uuid', None)

    return jsonify({'logout': True})

app/ui/routes/pages.py
from flask import Blueprint, render_template, session, redirect, url_for
from app.infra.actions import get_user_files, get_username

pages_blueprint = Blueprint('page', __name__)

@pages_blueprint.before_app_request
def ensire_login():
    if 'loged_in' not in session:
        session['loged_in'] = False
        session['uuid'] = None

@pages_blueprint.route('/')
def main_page():
    if not session['loged_in']:
        return redirect(url_for('page.login_page'))
    print(session['uuid'])
    return render_template('index.html', name=get_username(session['uuid']))

@pages_blueprint.route('/upload_page')
def upload_page():
    if not session['loged_in']:
        return redirect(url_for('page.login_page'))

    return render_template('upload.html')

@pages_blueprint.route('/download_page')
def download_page():
    if not session['loged_in']:
        return redirect(url_for('page.login_page'))

    return render_template("download.html", files=get_user_files(session['uuid']))

@pages_blueprint.route('/login')
def login_page():
    return render_template('login.html')

@pages_blueprint.route('/register.html')
def register_page():
    return render_template('register.html')

app/ui/routes/services.py
from flask import Blueprint, request, jsonify, current_app, session, send_file
from app.infra.actions import RegisterFile
from app.infra.actions import get_file_path_and_name
import uuid
import os

services_blueprint = Blueprint('service', __name__)

@services_blueprint.route('/upload', methods=['POST'])
def upload():
    if 'files' not in request.files:
        return jsonify({'success': False, 'error': 'Nenhum arquivo selecionado'}), 400

    files = request.files.getlist('files')

    if not files or files[0].filename == '':
        return jsonify({'success': False, 'error': 'Nenhum arquivo foi selecionado'}), 400

    for file in files:
        if file:
            file_name, file_extension = os.path.splitext(file.filename)
            file_uuid = uuid.uuid4()
            file_uuid_str = str(file_uuid) + file_extension
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], str(session['uuid']), file_uuid_str))
            registerFile = RegisterFile(filename=file_name, fileUuid=file_uuid, fileExtension=file_extension, userUuid=str(session['uuid']))
            registerFile.register()
    
    return jsonify({'success': True}), 200

@services_blueprint.route('/download/<int:file_uuid>')
def download(file_uuid):
    path, name = get_file_path_and_name(file_uuid=file_uuid)
    
    return send_file(path, as_attachment=True, download_name=name)

app/ui/templates/download.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/download.css') }}">
    <script src="{{ url_for('static', filename='js/download.js') }}" defer></script>
    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/download.css">
    <script src="../static/js/download.js"></script>
    <title>Download de Arquivo</title>
</head>
<body>
    <nav class="navBar">
        <a href="{{ url_for('page.main_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">home</span></a>
        <a href="{{ url_for('page.upload_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_upload</span></a>
        <a href="{{ url_for('page.download_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_download</span></a>
    </nav>
    <main class="mainContent">
        <div class="mainContentDownloads">
            {% for file in files %}
                <a href="{{ url_for('service.download', file_uuid=file[1]) }}" class="mainContentA">
                    <span class="material-symbols-outlined fileIcon">draft</span>
                    <span class="fileName">{{ file[0] }}</span>
                </a>
            {% endfor %}
        </div>
    </main>
</body>
</html>

app/ui/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <script src="{{ url_for('static', filename='js/index.js') }}" defer></script>
    <title>Inicio</title>
</head>
<body>
    <nav class="navBar">
        <a href="{{ url_for('page.main_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">home</span></a>
        <a href="{{ url_for('page.upload_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_upload</span></a>
        <a href="{{ url_for('page.download_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_download</span></a>
    </nav>
    <main class="mainContent">
        <p class="mainContentP">Logado como <strong class="name">{{ name }}</strong></p>
        <button id="logoutButton">Sair</button>
    </main>
</body>
</html>

app/ui/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <script src="{{ url_for('static', filename='js/login.js') }}" defer></script>
    <title>Login</title>
</head>
<body>
    <main class="mainContent">
        <h1 class="mainContentH1">Login</h1>
        <form id="LoginForm" action="" class="mainContentForm">
            <input type="user" class="mainContentFormInput" placeholder="Useuário" name="username">
            <input type="password" class="mainContentFormInput" placeholder="Senha" name="password">
        </form>
        <div class="mainContentDiv">
            <p>Não tem conta? clique <a href="{{ url_for('page.register_page') }}" class="mainContentDivPA">Aqui</a></p>
        </div>
        <button type="submit" form="LoginForm" class="LoginFormButton">Login</button>
    </main>
</body>
</html>

app/ui/templates/register.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}" defer>
    <script src="{{ url_for('static', filename='js/register.js') }}" defer></script>
    <title>Registrar</title>
</head>
<body>
    <main class="mainContent">
        <h1 class="mainContentH1">Registrar</h1>
        <form id="RegisterForm" action="" class="mainContentForm">
            <input type="text" class="mainContentFormInput" placeholder="Usuário" name="username">
            <input type="password" class="mainContentFormInput" placeholder="Senha" name="password">
        </form>
        <div class="mainContentDiv">
            <p>Já tem conta? clique <a href="{{ url_for('page.login_page') }}" class="mainContentDivPA">Aqui</a></p>
        </div>
        <button type="submit" form="RegisterForm" class="RegisterFormButton">Registrar</button>
    </main>
</body>
</html>

app/ui/templates/upload.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/upload.css') }}">
    <script src="{{ url_for('static', filename='js/upload.js') }}" defer></script>
    <title>Upload de Arquivo</title>
</head>
<body>
    <nav class="navBar">
        <a href="{{ url_for('page.main_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">home</span></a>
        <a href="{{ url_for('page.upload_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_upload</span></a>
        <a href="{{ url_for('page.download_page') }}" class="navBarA"><span class="material-symbols-outlined ASpan">cloud_download</span></a>
    </nav>
    <main class="mainContent">
        <div class="mainContentDiv">
            <h1 class="mainContentH1">Faça o upload de arquivos para o servidor para backup</h1>
            <label for="fileUpload" class="fileLabel">
                <span class="material-symbols-outlined fileLabelSpan">upload</span>
                <span class="fileUploadSpan">Escolher arquivo</span>
                <input type="file" id="fileUpload" name="file" class="fileInput">
            </label>
            <div id="messageContainer"></div>
        </div>
    </main>
</body>
</html>